Chat_spaceのサイドバーの作成
Kobatai/chat_space pull request #1
Opened 2019-01-27 12:21 UTC by Kobatai

#WHAT
Chat_spaceの画面設計にてサイドバーを実装する
#WHY
Chat_spaceのユーザー管理機能を実装するため

2019-01-27 12:26 UTC, ghost commented
実装した画面のキャプチャをこちらに添付してください

失礼しました！
<img width="1386" alt="2019-01-27 20 41 15" src="https://user-images.githubusercontent.com/46162925/51801128-1cbe4a00-227d-11e9-8172-8e47699eddee.png">

2019-01-27 12:29 UTC, ghost commented
app/views/layouts/.DS_Storeはgitignoreしてください

記述しました！

2019-01-27 12:31 UTC, ghost requested changes
DB設計ってもうやったんでしょうか・・・？

2019-01-27 12:31 UTC, hiroki5123 commented on app/assets/stylesheets/_side-bar.scss
> +//     background-color:#2f3e51;
ここら辺つかってないので荒れば削除しましょう

2019-01-27 12:31 UTC, hiroki5123 commented on app/assets/config/prepros-6.config
> +  "exportConfig": true,
このファイルって何ですか？

2019-01-27 12:31 UTC, hiroki5123 commented on config/routes.rb
> +  root  'messages_controller#index'
_controller必要ないかと思うのですがいかがでしょうか？

2019-01-27 12:31 UTC, hiroki5123 commented on app/views/shared/_sidebar.html.haml
> +      =link_to "groups/new", class: 'chat-side__user__new-group' do
ここは#で仮置きでいいと思います。

2019-01-27 12:50 UTC, Kobatai commented on app/assets/config/prepros-6.config
> +  "exportConfig": true,
preprosというアプリでScssをCSSに変換する変換した際にできたファイルです。

2019-01-27 12:52 UTC, Kobatai commented on app/assets/stylesheets/_side-bar.scss
> +//     background-color:#2f3e51;
> DB設計ってもうやったんでしょうか・・・？

申し訳ありません。
まだでしたのでそちらに取り掛かります。

2019-01-29 12:04 UTC, Kobatai commented on app/assets/stylesheets/_side-bar.scss
> +//     background-color:#2f3e51;
DB作成しました！

2019-01-29 12:13 UTC, Kobatai commented on config/routes.rb
> +  root  'messages_controller#index'
名前を変えるために一度messages_controllerを削除し、新たにmessagesでコントローラーを作成しました。

2019-01-29 12:13 UTC, ghost commented on app/assets/config/prepros-6.config
> +  "exportConfig": true,
そのままscssで書いてしまって大丈夫です。
railsではscssを自動でcssにコンパイルさせる機能が付いています。

2019-01-29 12:13 UTC, Kobatai commented on app/views/shared/_sidebar.html.haml
> +      =link_to "groups/new", class: 'chat-side__user__new-group' do
＃で仮置きしました！

2019-01-29 12:14 UTC, hiroki5123 commented on app/assets/stylesheets/prepros-6.config
> +  "name": "stylesheets",
このファイルは必要ないので削除しましょう

2019-01-29 12:14 UTC, hiroki5123 commented on app/assets/config/prepros-6.config
> +      "configJson": "{\"forceCompile\":false,\"customOutput\":\"../stylesheets/application.css\",\"autoCompile\":true,\"sourceMap\":false,\"compiler-node-sass\":{\"enabled\":true,\"outputStyle\":\"ne
このファイルも削除してください〜

2019-01-29 12:23 UTC, Kobatai commented on app/assets/stylesheets/prepros-6.config
> +  "name": "stylesheets",
削除しました！

2019-01-29 12:23 UTC, Kobatai commented on app/assets/config/prepros-6.config
> +      "configJson": "{\"forceCompile\":false,\"customOutput\":\"../stylesheets/application.css\",\"autoCompile\":true,\"sourceMap\":false,\"compiler-node-sass\":{\"enabled\":true,\"outputStyle\":\"ne
削除しました!

2019-01-30 09:22 UTC, yusukeyamane commented on app/assets/stylesheets/prepros-6.config
> +  "name": "stylesheets",
まだ削除出来てないようです！

2019-01-30 09:24 UTC, yusukeyamane commented on app/views/layouts/mailer.text.haml
> += yield
このviewファイルは使用していないと思うので削除しましょう

2019-01-30 09:25 UTC, yusukeyamane commented on README.md
> +|mail|string|null: false|
パスワードを保存するフィールドも欲しいですね！

2019-01-30 09:26 UTC, yusukeyamane commented on README.md
> +- has_many :users
has_many :users, through: :members
ですね！

2019-01-30 09:27 UTC, k-taiga commented on app/assets/stylesheets/prepros-6.config
> +  "name": "stylesheets",
大変失礼いたしました！　先ほど削除したあとコミットしましたので、ご確認よろしくお願いします。

2019-01-30 09:27 UTC, yusukeyamane commented on README.md
> +- has_many :groups
has_many :groups, through: :members
ですね！

2019-01-30 09:27 UTC, yusukeyamane commented on app/assets/stylesheets/application.css
> +body,
このあたりの記述って_reset.css.scssと被っていませんか？

2019-01-30 11:23 UTC, Kobatai commented on app/views/layouts/mailer.text.haml
> += yield
削除しました！

2019-01-30 11:24 UTC, k-taiga commented on README.md
> +|mail|string|null: false|
パスワードのカラム、追加しました。

2019-01-30 11:26 UTC, k-taiga commented on README.md
> +- has_many :users
追記しました。　membersテーブルを第3のモデルとして、そこを経由して多対多を関連づけるのですね！

2019-01-30 11:26 UTC, k-taiga commented on README.md
> +- has_many :groups
こちらも追記しました！

2019-01-30 12:00 UTC, Kobatai commented on app/assets/stylesheets/application.css
> +body,
修正いたしました。

2019-01-30 12:04 UTC, yusukeyamane commented
LGTMです！

2019-01-30 12:07 UTC, Kobatai commented
ありがとうございます！！！！！

2019-01-30 12:07 UTC, merged