メッセージ送信機能の非同期通信化
Kobatai/chat_space pull request #8
Opened 2019-02-17 09:50 UTC by Kobatai

#WHAT
メッセージ送信機能を非同期で行うためにjQueryを実装する

#WHY
画面をリアルタイムで更新するため

2019-02-17 10:09 UTC, ghost requested changes

2019-02-17 10:09 UTC, hiroki5123 commented on app/views/groups/_form.html.haml
> +        %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", :type => "text"}/
ハッシュロケットを書かないようにしましょう

2019-02-17 10:09 UTC, hiroki5123 commented on app/views/groups/_form.html.haml
> +      %label.chat-group-form__label{:for => "chat_group_チャットメンバーを追加"} チャットメンバーを追加
ハッシュロケットを書かないようにしましょう

2019-02-17 10:09 UTC, hiroki5123 commented on app/assets/javascripts/message.js
> +                    ${ message.image }
これで画像表示されるのでしょうか。。。？

2019-02-17 10:09 UTC, hiroki5123 commented on app/assets/javascripts/message.js
> +  $(`.chat-main__footer-form`).on(`submit`,function(e){
この指定で非同期になってますか？

2019-02-17 10:09 UTC, hiroki5123 commented
すみません、下記の部分も含めてGIFをとってもう一回こちらに貼ってもらってもいいでしょうか？
[![Screenshot from Gyazo](https://gyazo.com/cd2c138b0d5a49f6496175798c51bff9/raw)](https://gyazo.com/cd2c138b0d5a49f6496175798c51bff9)

2019-02-17 10:37 UTC, Kobatai commented on app/views/groups/_form.html.haml
> +        %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", :type => "text"}/
修正しました！

2019-02-17 10:37 UTC, Kobatai commented on app/views/groups/_form.html.haml
> +      %label.chat-group-form__label{:for => "chat_group_チャットメンバーを追加"} チャットメンバーを追加
修正しました！

2019-02-17 10:40 UTC, Kobatai commented
動画二本に別れてしまったのですが、こちらでどうでしょうか？
１.https://gyazo.com/07fc66faa710a664eb0a12a4b06464f4
２.https://gyazo.com/65ccd9e2aa6ef05cfffaf38c1f854b80

2019-02-17 10:42 UTC, Kobatai commented on app/assets/javascripts/message.js
> +                    ${ message.image }
画像は表示できてます！

2019-02-17 10:46 UTC, hiroki5123 commented
Gyazoを貼っていただきありがとうございます。
やはり非同期になっていないようですので、修正をお願い致します。
どこで判断したかというと、送信ボタンを押した時に再読み込みのボタンの部分が一瞬バツマークになっているので、非同期ではなく同期通信が行われていることがわかります。

2019-02-19 11:34 UTC, Kobatai commented
丁寧なご指摘ありがとうございます。
いただいたご指摘を参考にコードを修正し、非同期で通信できるようになったかと思うので↓のご確認をよろしくお願いいたします！
1.https://gyazo.com/9d05cd91bc97aa8d7049d06b02774c08
2.https://gyazo.com/0e32633add86a46f47c5975e08f3e4f4

2019-02-19 11:44 UTC, ghost requested changes

2019-02-19 11:44 UTC, hiroki5123 commented on app/controllers/messages_controller.rb
> +  class MessagesController < ApplicationController
インデントずれてます
左に詰めてください

2019-02-19 11:46 UTC, Kobatai commented on app/controllers/messages_controller.rb
> +  class MessagesController < ApplicationController
修正しました！

2019-02-19 12:00 UTC, ReoKuriyama approved these changes
一点だけ修正していただいたらマージして大丈夫です！

2019-02-19 12:00 UTC, ReoKuriyama commented on app/controllers/messages_controller.rb
> +        format.html { redirect_to group_messages_path(@group) }
htmlのレスポンスはもう使わないので消しましょう。

2019-02-19 12:09 UTC, Kobatai commented on app/controllers/messages_controller.rb
> +        format.html { redirect_to group_messages_path(@group) }
レビューありがとうございます！
レスポンスの修正しましたので、マージいたします。

2019-02-19 12:19 UTC, merged